language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - ./gradlew build
deploy:
  provider: releases
  api_key:
    secure: lWodS5ZTdGPcnF1MGtpYAU3hH6bpJ0t0213eEdF0iWssq1e3mW/RBJMQFn2GYuPobbe3ngdu5/VJtn9XjPHTU0ON4pr6bFN1bYkcwBzq9gjYU4q0E2jIWm4Ga9gQh4kJpLzbaQ3hGdF52r5dX/wwPun1lhPJoPGAJvtxfqv9HrRhvWmxzjmEAweVrnwJQ6ZAhyQmCkVrfBb8dl46U9qiUr+/6c4pjTLriAbP+FngZkAG2kSKnR6ElVufE2EUWknaY2Scka45OJyMqaQCLXQSH0Kpvmx/uERfDjJPvP5lFrqKt7VNN5V3sAzKAY8+LO22bQWxJjZz2tp68IB/7YkkrsHAy14LqyguN0dHJAKHuDVONv9+o+WkBS7V0IIZR4mZKGMbNCAdqQCGEnTNXBfZrTlDbTFLLwCv9DnyHEM0hFQ676dbCNEXrNDtGwnQHnvLIk+A2XORWgqdPqLZ7ZXpYqbuLhWxXbmEPMZk334wQcfppspRbGNJPHoCP0vVS0o5LlUu+6HjMQgR+yn0lY+hDKp1btA9TPCrj1kt4V6VVNY5/K00Qex0GEgRpycsVS4yTaeNYQ95/46JRVQCd1MTJAde36IV4PG/jpEzhDavNnv/dns67OUW7SWgCTTaAQK2/MSf09ppfMDQu8OfQc2dzfoA+7jvUoWbu71Qc9Woo4E=
  file: app/build/outputs/apk/app-debug.apk
  on:
    repo: YeungKC/Gank.io-for-Kotlin-Android
